CREATE TABLE payment_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   customer_id VARCHAR(255) NOT NULL,
   type VARCHAR(255) NOT NULL,
   status VARCHAR(255) NOT NULL,
   value_cents BIGINT NOT NULL,
   payment_reference VARCHAR(255) NOT NULL,
   created_at TIMESTAMP with time zone,
   updated_at TIMESTAMP with time zone,
   CONSTRAINT pk_payment_requests PRIMARY KEY (id)
);